apiVersion: v1
kind: Namespace
metadata:
  name: kube-demo-ns

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: kube-demo-ns
data:
  database_url: mongodb-service
# database_url: mongodb-service.kube-demo // sharing ns resources except configMap and secrets